/**
 * Tiny sound-effect service. Pooled lazy players over bundled WAVs
 * (generated by scripts/generate-sfx.mjs).
 *
 * Rules:
 * - Never touches setAudioModeAsync — talk.tsx owns the audio session dance.
 * - Never throws: a missing/failed sound must never break gameplay.
 * - Respects the `soundEnabled` setting.
 */
import { createAudioPlayer, type AudioPlayer } from 'expo-audio';

import { useSettings } from '@/store/settings';

const SOURCES = {
  success: require('../../assets/sfx/success.wav'),
  error: require('../../assets/sfx/error.wav'),
  tick: require('../../assets/sfx/tick.wav'),
  fanfare: require('../../assets/sfx/fanfare.wav'),
  boop: require('../../assets/sfx/boop.wav'),
} as const;

export type SfxName = keyof typeof SOURCES;

const pool = new Map<SfxName, AudioPlayer>();

export function playSfx(name: SfxName, volume = 1) {
  if (!useSettings.getState().soundEnabled) return;
  try {
    let player = pool.get(name);
    if (!player) {
      player = createAudioPlayer(SOURCES[name]);
      pool.set(name, player);
    }
    player.volume = volume;
    player.seekTo(0); // retrigger from the start — fine for rapid ticks
    player.play();
  } catch {
    // SFX must never crash gameplay
  }
}
