import { and, eq, gte } from 'drizzle-orm';

import type { Analysis } from '../ai/analysis.js';
import {
  GENERATOR_MODEL,
  currentSeason,
  generateWeekPlan,
  type GeneratorInput,
} from '../ai/generator.js';
import { getDb } from '../db/client.js';
import { children, generatedWeeks, type LessonContent } from '../db/schema.js';

/**
 * Progressive AI curriculum for learners the curated *beginner* static content
 * does not fit. Only beginner kid templates exist in the pool, so anyone above
 * beginner — or a teen/adult — would otherwise be silently served a 7-year-old's
 * "hello / name / house" plan. Those children instead get a level- and age-aware
 * curriculum generated by the same engine that powers days 31+, built one week at
 * a time: week 1 synchronously (immediate first lesson), the rest in the
 * background so the up-front wait stays to a single LLM call.
 */

// Weeks 1..5 cover days 1..35; the child uses days 1..30, and week 5 (days 31-35)
// then seamlessly continues the normal day-31+ flow (same weekNumber scheme).
const LAST_CURRICULUM_WEEK = 5;

export function needsGeneratedCurriculum(_level?: string, _ageBand?: string | null): boolean {
  // Policy (2026-06-30): EVERY learner gets an AI-built curriculum keyed to their
  // level, age, interests, and goal — not a one-size-fits-all beginner pool. The
  // bundled static days 1-30 remain only as an offline / pre-fetch safety net.
  //
  // Because this is unconditionally `true`, every `else` branch guarded by it —
  // the entire personalize.ts / child_curricula "interest-skinning" subsystem
  // (Phase 25) — is RETAINED FALLBACK ONLY, never executed for a real child.
  // It's intentionally kept (not dead code) so flipping this flag off re-enables
  // static serving. Physical removal is a separate, deliberate task — see
  // context/CLEANUP-personalize-legacy.md.
  return true;
}

/** A brand-new child has no conversations/errors to analyse — seed an empty
 * analysis carrying only their stated interests (the generator keys off these). */
function seedAnalysis(interests: string[]): Analysis {
  return {
    strengths: [],
    weaknesses: [],
    vocabularyToReview: [],
    conversationTopics: [],
    interests: interests.slice(0, 8),
    suggestedFocus: [],
  };
}

// In-process dedup: a week can be requested concurrently by the background
// pre-generation and an on-demand read. Share the one in-flight promise so we
// never pay for the same LLM week twice (the unique constraint would dedup the
// rows, but not the cost / latency).
const inFlight = new Map<string, Promise<boolean>>();

/**
 * Generate one 7-day week of leveled curriculum and store it as an (approved)
 * generated week. Idempotent: returns early if the week already exists. Returns
 * true on success (or already present), false if the child is gone / generation
 * failed (caller decides whether to surface a "not ready yet" state).
 */
export async function generateCurriculumWeek(
  childId: string,
  language: 'en' | 'ru',
  weekNumber: number,
): Promise<boolean> {
  const key = `${childId}:${language}:${weekNumber}`;
  const running = inFlight.get(key);
  if (running) return running;
  const promise = doGenerateCurriculumWeek(childId, language, weekNumber);
  inFlight.set(key, promise);
  try {
    return await promise;
  } finally {
    inFlight.delete(key);
  }
}

/** Assemble GeneratorInput for a child + arbitrary day range, with theme dedup. */
async function buildGeneratorInput(
  childId: string,
  language: 'en' | 'ru',
  weekNumber: number,
  startDay: number,
  endDay: number,
  extraRecentThemes: string[] = [],
): Promise<{ input: GeneratorInput; analysis: Analysis } | null> {
  const db = getDb();
  const [child] = await db.select().from(children).where(eq(children.id, childId)).limit(1);
  if (!child) return null;

  // Avoid repeating themes already generated for this child.
  const prior = await db
    .select({ lessons: generatedWeeks.lessons })
    .from(generatedWeeks)
    .where(and(eq(generatedWeeks.childId, childId), eq(generatedWeeks.language, language)));
  const recentThemes = [
    ...prior.flatMap((w) => w.lessons.map((l) => l.theme)),
    ...extraRecentThemes,
  ];

  const analysis = seedAnalysis(child.interests ?? []);
  const input: GeneratorInput = {
    childName: child.name,
    childAge: child.age,
    level: child.level,
    language,
    startDay,
    endDay,
    weekNumber,
    analysis,
    recentThemes,
    season: currentSeason(),
    prefs: child.lessonPrefs ?? undefined,
    ageBand: (child.ageBand as GeneratorInput['ageBand']) ?? undefined,
    goal: child.goal ?? undefined,
    goals: child.goals?.length ? child.goals : child.goal ? [child.goal] : undefined,
    activeDaysPerWeek: child.scheduleDays?.length || undefined,
  };
  return { input, analysis };
}

function fetchWeekRow(childId: string, language: 'en' | 'ru', weekNumber: number) {
  const db = getDb();
  return db
    .select({ id: generatedWeeks.id, lessons: generatedWeeks.lessons })
    .from(generatedWeeks)
    .where(
      and(
        eq(generatedWeeks.childId, childId),
        eq(generatedWeeks.language, language),
        eq(generatedWeeks.weekNumber, weekNumber),
      ),
    )
    .limit(1);
}

async function doGenerateCurriculumWeek(
  childId: string,
  language: 'en' | 'ru',
  weekNumber: number,
): Promise<boolean> {
  const db = getDb();

  const [existing] = await fetchWeekRow(childId, language, weekNumber);
  if (existing) {
    // Week 1 can exist as a fast partial (day 1 only) — finish it instead of
    // silently treating it as done (the insert below would no-op on conflict).
    if (weekNumber === 1 && existing.lessons.length < 7) {
      return completeWeekOne(childId, language);
    }
    return true;
  }

  const startDay = (weekNumber - 1) * 7 + 1;
  const endDay = startDay + 6;
  const built = await buildGeneratorInput(childId, language, weekNumber, startDay, endDay);
  if (!built) return false;

  try {
    const plan = await generateWeekPlan(built.input);
    await db
      .insert(generatedWeeks)
      .values({
        childId,
        language,
        weekNumber,
        startDay,
        endDay,
        lessons: plan.lessons,
        analysis: built.analysis,
        weekRationale: plan.weekRationale,
        status: 'approved', // initial curriculum is auto-live; parent feedback re-tunes future weeks
        model: GENERATOR_MODEL,
      })
      .onConflictDoNothing();
    return true;
  } catch {
    return false; // transient LLM failure — re-attempted lazily on next read
  }
}

/**
 * FAST first-lesson path: generate ONLY day 1 (a single small LLM call, seconds
 * instead of a full-week wait) and store it as a partial week-1 row. The rest of
 * week 1 is filled by completeWeekOne in the background.
 */
export async function generateCurriculumDayOne(
  childId: string,
  language: 'en' | 'ru',
): Promise<boolean> {
  const key = `${childId}:${language}:day1`;
  const running = inFlight.get(key);
  if (running) return running;
  const promise = doGenerateDayOne(childId, language);
  inFlight.set(key, promise);
  try {
    return await promise;
  } finally {
    inFlight.delete(key);
  }
}

async function doGenerateDayOne(childId: string, language: 'en' | 'ru'): Promise<boolean> {
  const db = getDb();
  const [existing] = await fetchWeekRow(childId, language, 1);
  if (existing) return true; // partial or full — day 1 is there either way

  const built = await buildGeneratorInput(childId, language, 1, 1, 1);
  if (!built) return false;

  try {
    const plan = await generateWeekPlan(built.input); // exactly 1 lesson
    await db
      .insert(generatedWeeks)
      .values({
        childId,
        language,
        weekNumber: 1,
        startDay: 1,
        endDay: 7,
        lessons: plan.lessons,
        analysis: built.analysis,
        weekRationale: plan.weekRationale,
        status: 'partial', // days 2-7 pending — completeWeekOne flips to 'approved'
        model: GENERATOR_MODEL,
      })
      .onConflictDoNothing();
    return true;
  } catch {
    return false;
  }
}

/**
 * Complete a partial week 1 (day 1 already generated) with days 2-7, passing
 * day-1's theme as context so the week continues coherently. UPDATEs the
 * existing row (merge + sort) and marks it approved.
 */
export async function completeWeekOne(childId: string, language: 'en' | 'ru'): Promise<boolean> {
  const key = `${childId}:${language}:w1complete`;
  const running = inFlight.get(key);
  if (running) return running;
  const promise = doCompleteWeekOne(childId, language);
  inFlight.set(key, promise);
  try {
    return await promise;
  } finally {
    inFlight.delete(key);
  }
}

async function doCompleteWeekOne(childId: string, language: 'en' | 'ru'): Promise<boolean> {
  const db = getDb();
  const [row] = await fetchWeekRow(childId, language, 1);
  if (!row) {
    // No partial to complete — fall back to generating the full week.
    return generateCurriculumWeek(childId, language, 1);
  }
  if (row.lessons.length >= 7) return true;

  const haveDays = new Set(row.lessons.map((l) => l.day));
  const built = await buildGeneratorInput(childId, language, 1, 2, 7);
  if (!built) return false;

  try {
    const plan = await generateWeekPlan(built.input); // days 2-7 (6 lessons)
    const merged = [...row.lessons, ...plan.lessons.filter((l) => !haveDays.has(l.day))].sort(
      (a, b) => a.day - b.day,
    );
    await db
      .update(generatedWeeks)
      .set({ lessons: merged, status: 'approved' })
      .where(eq(generatedWeeks.id, row.id));
    return true;
  } catch {
    return false; // retried by the next curriculum read (partial week triggers completion)
  }
}

/**
 * Ensure a leveled curriculum exists. DAY 1 is generated synchronously (one
 * small LLM call — the child can start within seconds); days 2-7 and weeks
 * 2..5 fill in the background.
 */
export async function ensureGeneratedCurriculum(
  childId: string,
  languages: string[],
): Promise<void> {
  await Promise.all(
    languages.map(async (lang) => {
      const l = lang as 'en' | 'ru';
      await generateCurriculumDayOne(childId, l).catch(() => {});
      // Fire-and-forget the rest so child creation / first fetch isn't blocked.
      void (async () => {
        await completeWeekOne(childId, l).catch(() => {});
        for (let w = 2; w <= LAST_CURRICULUM_WEEK; w++) {
          await generateCurriculumWeek(childId, l, w).catch(() => {});
        }
      })();
    }),
  );
}

/**
 * Parent gave feedback (new prefs/interests): wipe the not-yet-reached weeks and
 * regenerate them so the change is honored going forward — never touching a day
 * the child has already seen. The immediate next week is regenerated
 * synchronously; the rest of the existing horizon refills in the background.
 */
export async function regenerateGeneratedCurriculumFrom(
  childId: string,
  languages: string[],
  fromDay: number,
): Promise<void> {
  const db = getDb();
  const weekStart = Math.max(1, Math.ceil(fromDay / 7));

  await Promise.all(
    languages.map(async (lang) => {
      const l = lang as 'en' | 'ru';
      const existing = await db
        .select({ weekNumber: generatedWeeks.weekNumber })
        .from(generatedWeeks)
        .where(and(eq(generatedWeeks.childId, childId), eq(generatedWeeks.language, l)));
      const maxWeek = existing.reduce((m, w) => Math.max(m, w.weekNumber), LAST_CURRICULUM_WEEK);

      await db
        .delete(generatedWeeks)
        .where(
          and(
            eq(generatedWeeks.childId, childId),
            eq(generatedWeeks.language, l),
            gte(generatedWeeks.weekNumber, weekStart),
          ),
        );

      await generateCurriculumWeek(childId, l, weekStart).catch(() => {});
      void (async () => {
        for (let w = weekStart + 1; w <= maxWeek; w++) {
          await generateCurriculumWeek(childId, l, w).catch(() => {});
        }
      })();
    }),
  );
}

/** Drop the day/reasoning fields so a generated lesson matches the shape the
 * curriculum endpoints serve (LessonContent). */
function toLessonContent(lesson: { day: number; reasoning: string } & LessonContent): LessonContent {
  const { day: _day, reasoning: _reasoning, ...content } = lesson;
  return content;
}

/** Single generated curriculum day. Generates the covering week on demand if it
 * isn't ready yet (e.g. a background week that hasn't finished). */
export async function getGeneratedCurriculumDay(
  childId: string,
  language: 'en' | 'ru',
  day: number,
): Promise<LessonContent | null> {
  const db = getDb();
  const weekNumber = Math.ceil(day / 7);

  const fetchWeek = () =>
    db
      .select({ lessons: generatedWeeks.lessons })
      .from(generatedWeeks)
      .where(
        and(
          eq(generatedWeeks.childId, childId),
          eq(generatedWeeks.language, language),
          eq(generatedWeeks.weekNumber, weekNumber),
        ),
      )
      .limit(1);

  let [week] = await fetchWeek();
  if (!week) {
    await generateCurriculumWeek(childId, language, weekNumber);
    [week] = await fetchWeek();
  }
  let lesson = week?.lessons.find((l) => l.day === day);
  if (!lesson && week && weekNumber === 1) {
    // Partial week 1 (fast day-1 path): the requested day is still pending —
    // finish the week now and re-read.
    await completeWeekOne(childId, language);
    [week] = await fetchWeek();
    lesson = week?.lessons.find((l) => l.day === day);
  }
  return lesson ? toLessonContent(lesson) : null;
}

/** All generated curriculum days 1..30 for the batch endpoint, kicking off any
 * still-missing weeks in the background. */
export async function getGeneratedCurriculumAll(
  childId: string,
  language: 'en' | 'ru',
): Promise<{ day: number; content: LessonContent }[]> {
  const db = getDb();
  await generateCurriculumDayOne(childId, language); // guarantee an immediate day 1

  const weeks = await db
    .select({ lessons: generatedWeeks.lessons })
    .from(generatedWeeks)
    .where(and(eq(generatedWeeks.childId, childId), eq(generatedWeeks.language, language)));

  const out: { day: number; content: LessonContent }[] = [];
  for (const w of weeks) {
    for (const l of w.lessons) {
      if (l.day >= 1 && l.day <= 30) out.push({ day: l.day, content: toLessonContent(l) });
    }
  }
  out.sort((a, b) => a.day - b.day);

  // Finish week 1 + fill any missing weeks (2..5) in the background for next time.
  void (async () => {
    await completeWeekOne(childId, language).catch(() => {});
    for (let wk = 2; wk <= LAST_CURRICULUM_WEEK; wk++) {
      await generateCurriculumWeek(childId, language, wk).catch(() => {});
    }
  })();

  return out;
}
